In [1]:
import pandas as pd
import numpy as np

In [2]:
data1 = pd.read_csv('D:\\GitHub\\Airbnb\\Feature Mapping + Sentiment\\Final_Reviewer_Scores.csv', error_bad_lines=False, encoding='latin-1')
data2 = pd.read_csv('D:\\GitHub\\Airbnb\\Feature Mapping + Sentiment\\temp_overall.csv', error_bad_lines=False)

In [3]:
data = pd.merge(data1,data2, how = "inner", on = ["listing_id", "reviewer_id"])

In [8]:
data.head()
#len(data)

listing_id  reviewer_id  experience     view  décor_and_amenities  \
0       35644      5394983         NaN  0.91525               0.9371   
1       35644      3712269         NaN  0.82710               0.8271   
2       35644      2908896         NaN      NaN                  NaN   
3       35644      3941752      0.5719  0.30890               0.5106   
4       35644      2735578         NaN      NaN                  NaN   

   neighborhood_and_access     host  weather_and_amenties    food  overall_avg  
0                   0.5115 -0.29600                   NaN  0.8225      0.58925  
1                   0.8271  0.54130                   NaN     NaN      0.59010  
2                      NaN  0.61850                   NaN     NaN      0.64045  
3                      NaN  0.91000                0.5719     NaN      0.57535  
4                      NaN  0.82475                   NaN  0.8479      0.82475

In [4]:
interaction_matrix = np.array(data.pivot(index = 'reviewer_id', columns ='listing_id', values = 'overall_avg').fillna(0))

In [6]:
print(interaction_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
#check if values exist
pd.DataFrame(interaction_matrix)[1].sum()

87.35422579365078

In [19]:
#y = pd.DataFrame(interaction_matrix)
#y.head()
data.pivot(index = 'reviewer_id', columns ='listing_id', values = 'overall_avg')
#x = data.loc[(data['listing_id']==35644) | (data['reviewer_id']==3712269),:]
#x.pivot(index = 'reviewer_id', columns ='listing_id', values = 'overall_avg')

listing_id   35644     38951     84581     88873     137808    162081    \
reviewer_id                                                               
1510              NaN       NaN       NaN       NaN       NaN       NaN   
6450              NaN       NaN       NaN       NaN       NaN       NaN   
6499              NaN       NaN       NaN       NaN       NaN       NaN   
6888              NaN       NaN       NaN       NaN       NaN       NaN   
7428              NaN       NaN       NaN       NaN       NaN       NaN   
8348              NaN       NaN       NaN       NaN       NaN       NaN   
10878             NaN       NaN       NaN       NaN       NaN       NaN   
11070             NaN       NaN       NaN       NaN       NaN       NaN   
12031             NaN       NaN       NaN       NaN       NaN       NaN   
12289             NaN       NaN       NaN       NaN       NaN       NaN   
13056             NaN       NaN       NaN       NaN       NaN       NaN   
15418             NaN       NaN       NaN       NaN       NaN       NaN   
16282             NaN       NaN       NaN       NaN       NaN       NaN   
16581             NaN       NaN       NaN       NaN       NaN       NaN   
16897             NaN       NaN       NaN       NaN       NaN       NaN   
17284             NaN       NaN       NaN       NaN       NaN       NaN   
17788             NaN       NaN       NaN       NaN       NaN       NaN   
18124             NaN       NaN       NaN       NaN       NaN       NaN   
20066             NaN       NaN       NaN       NaN       NaN       NaN   
20258             NaN       NaN       NaN       NaN       NaN       NaN   
21050             NaN       NaN       NaN       NaN       NaN       NaN   
21345             NaN       NaN       NaN       NaN       NaN       NaN   
21356             NaN       NaN       NaN       NaN       NaN       NaN   
21592             NaN       NaN       NaN       NaN       NaN       NaN   
21595             NaN       NaN       NaN       NaN       NaN       NaN   
22034             NaN       NaN       NaN       NaN       NaN       NaN   
22277             NaN       NaN       NaN       NaN       NaN       NaN   
22444             NaN       NaN       NaN       NaN       NaN       NaN   
22775             NaN       NaN       NaN       NaN       NaN       NaN   
22961             NaN       NaN       NaN       NaN       NaN       NaN   
...               ...       ...       ...       ...       ...       ...   
224921493         NaN       NaN       NaN       NaN       NaN       NaN   
224947715         NaN       NaN       NaN       NaN       NaN       NaN   
225062659         NaN       NaN       NaN       NaN       NaN       NaN   
225068903         NaN       NaN       NaN       NaN       NaN       NaN   
225069612         NaN       NaN       NaN       NaN       NaN       NaN   
225076174         NaN       NaN       NaN       NaN       NaN       NaN   
225164550         NaN       NaN       NaN       NaN       NaN       NaN   
225175617         NaN       NaN       NaN       NaN       NaN       NaN   
225187998         NaN       NaN       NaN       NaN       NaN       NaN   
225284075         NaN       NaN       NaN       NaN       NaN       NaN   
225295321         NaN       NaN       NaN       NaN       NaN       NaN   
225313744         NaN       NaN       NaN       NaN       NaN       NaN   
225332106         NaN       NaN       NaN       NaN       NaN       NaN   
225334043         NaN       NaN       NaN       NaN       NaN       NaN   
225334838         NaN       NaN       NaN       NaN       NaN       NaN   
225356445         NaN       NaN       NaN       NaN       NaN       NaN   
225461895         NaN       NaN       NaN       NaN       NaN       NaN   
225504727         NaN       NaN       NaN       NaN       NaN       NaN   
225530154         NaN       NaN       NaN       NaN       NaN       NaN   
225666125         NaN       NaN       NaN       NaN       NaN       NaN   
225673423         NaN    

In [25]:
#Count number of feature wise scores available for each reviewer
user_profile = pd.DataFrame({'reviewer_id':data.reviewer_id.unique()})
loop = ["experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food"]
for i in range(len(loop)):
    non_zero = data.loc[data[loop[i]]!=0]
    data_grouped = non_zero.groupby('reviewer_id')[loop[i]].apply(lambda x: pd.Series([x.count()])).unstack()
    print(i)
    user_profile = pd.merge(user_profile,data_grouped[0], how = 'left', on = 'reviewer_id')

0
1
2
3
4
5
6


In [29]:
user_profile.columns = ['reviewer_id',"experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food"]

In [34]:
#If available count of feature score > 0 for a user, mark as 1, else 0
user_profile_agg = user_profile
loop = ["experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food"]
for i in range(len(loop)):
    user_profile_agg.loc[user_profile_agg[loop[i]]>0,loop[i]] = 1

In [35]:
user_profile_agg.head()

reviewer_id  experience  view  décor_and_amenities  \
0      5394983           0   1.0                  1.0   
1      3712269           0   1.0                  1.0   
2      2908896           0   0.0                  0.0   
3      3941752           1   1.0                  1.0   
4      2735578           0   1.0                  1.0   

   neighborhood_and_access  host  weather_and_amenties  food  
0                      1.0     1                   0.0     1  
1                      1.0     1                   0.0     0  
2                      0.0     1                   0.0     0  
3                      0.0     1                   1.0     0  
4                      1.0     1                   0.0     1

In [48]:
listing_data = pd.DataFrame({'listing_id':data.listing_id.unique()})
loop = ["experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food","overall_avg"]
for i in range(len(loop)):
    data_grouped = data.groupby('listing_id')[loop[i]].apply(lambda x: pd.Series([(x < 0).sum(),(x > 0).sum()])).unstack()
    data_grouped['perc']=(data_grouped[1]-data_grouped[0])/(data_grouped[1]+data_grouped[0])
    print(i)
    listing_data = pd.merge(listing_data, data_grouped, how = 'left', on = 'listing_id')

0
1
2
3
4
5
6
7


In [49]:
listing_data.head()

listing_id  0_x  1_x    perc_x  0_y  1_y    perc_y  0_x  1_x    perc_x  \
0       35644    1   65  0.969697    1  130  0.984733    1  171  0.988372   
1       38951    0   30  1.000000    0   54  1.000000    3  105  0.944444   
2       84581    0    5  1.000000    0   14  1.000000    0   13  1.000000   
3       88873    2   25  0.851852    3   78  0.925926    7  235  0.942149   
4      137808    0   11  1.000000    2   20  0.818182    3  118  0.950413   

   ...    perc_x  0_y  1_y    perc_y  0_x  1_x    perc_x  0_y  1_y    perc_y  
0  ...  0.950000    0   60  1.000000    0   46  1.000000    3  198  0.970149  
1  ...  0.959184    3   36  0.846154    1   15  0.875000    0  135  1.000000  
2  ...  1.000000    0    7  1.000000    0    1  1.000000    0   16  1.000000  
3  ...  0.963636    5   63  0.852941    3   41  0.863636    2  296  0.986577  
4  ...  0.829787    5   18  0.565217    2   10  0.666667    4  139  0.944056  

[5 rows x 25 columns]

In [63]:
orig_data = pd.read_csv('D:\\GitHub\\Airbnb\\Recommendation\\Tasmania-detailed listings - final2.csv', error_bad_lines=False)
listing_profile = pd.merge(orig_data, listing_data, how = 'left', on = 'listing_id')

In [65]:
listing_profile.columns = ['listing_id','host_is_superhost','neighbourhood_cleansed','property_type','room_type','accommodates','bathrooms','bedrooms','beds','bed_type','price','security_deposit (% of price)','cleaning_fee (% of price)','minimum_nights','cancellation_policy',
"experience_p","experience_n","experience","view_p","view_n","view","décor_and_amenities_p","décor_and_amenities_n","décor_and_amenities",
"neighborhood_and_access_p","neighborhood_and_access_n","neighborhood_and_access","host_p","host_n","host",
"weather_and_amenties_p","weather_and_amenties_n","weather_and_amenties","food_p","food_n","food","overall_avg_p","overall_avg_n","overall_avg"]
features = ['listing_id','host_is_superhost','neighbourhood_cleansed','property_type','room_type','accommodates','bathrooms','bedrooms','beds','bed_type','price','security_deposit (% of price)','cleaning_fee (% of price)','minimum_nights','cancellation_policy',
"experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food","overall_avg"]
listing_profile = listing_profile[features]

In [66]:
listing_profile.head()

listing_id host_is_superhost neighbourhood_cleansed property_type  \
0       35644                 t                 Hobart         House   
1       38951                 t                 Hobart     Townhouse   
2       84581                 f                Kentish         House   
3       88873                 t                 Hobart     Townhouse   
4      137808                 f             Launceston         House   

         room_type  accommodates  bathrooms  bedrooms  beds  bed_type  ...  \
0     Private room             2        1.5         1     1  Real Bed  ...   
1  Entire home/apt             4        1.0         2     2  Real Bed  ...   
2  Entire home/apt             9        2.0         3     6  Real Bed  ...   
3  Entire home/apt             4        1.0         2     3  Real Bed  ...   
4  Entire home/apt             9        1.5         2     7  Real Bed  ...   

  minimum_nights          cancellation_policy experience      view  \
0              1                     moderate   0.969697  0.984733   
1              2  strict_14_with_grace_period   1.000000  1.000000   
2              2  strict_14_with_grace_period   1.000000  1.000000   
3              1                     moderate   0.851852  0.925926   
4              1  strict_14_with_grace_period   1.000000  0.818182   

  décor_and_amenities  neighborhood_and_access      host  \
0            0.988372                 0.974359  0.950000   
1            0.944444                 0.983740  0.959184   
2            1.000000                 1.000000  1.000000   
3            0.942149                 0.961240  0.963636   
4            0.950413                 0.882353  0.829787   

   weather_and_amenties      food  overall_avg  
0              1.000000  1.000000     0.970149  
1              0.846154  0.875000     1.000000  
2              1.000000  1.000000     1.000000  
3              0.852941  0.863636     0.986577  
4              0.565217  0.666667     0.944056  

[5 rows x 23 columns]

In [67]:
listing_profile.to_csv('D:\\GitHub\\Airbnb\\Recommendation\\Tasmania-FinalDataset.csv')