In [356]:
import pandas as pd
import numpy as np
import scipy
from lightfm.data import Dataset
from lightfm import LightFM

In [2]:
data1 = pd.read_csv('D:\\GitHub\\Airbnb\\Feature Mapping + Sentiment\\Final_Reviewer_Scores.csv', error_bad_lines=False, encoding='latin-1')
data2 = pd.read_csv('D:\\GitHub\\Airbnb\\Feature Mapping + Sentiment\\temp_overall.csv', error_bad_lines=False)

In [3]:
data = pd.merge(data1,data2, how = "inner", on = ["listing_id", "reviewer_id"])

In [8]:
data.head()
#len(data)

listing_id  reviewer_id  experience     view  décor_and_amenities  \
0       35644      5394983         NaN  0.91525               0.9371   
1       35644      3712269         NaN  0.82710               0.8271   
2       35644      2908896         NaN      NaN                  NaN   
3       35644      3941752      0.5719  0.30890               0.5106   
4       35644      2735578         NaN      NaN                  NaN   

   neighborhood_and_access     host  weather_and_amenties    food  overall_avg  
0                   0.5115 -0.29600                   NaN  0.8225      0.58925  
1                   0.8271  0.54130                   NaN     NaN      0.59010  
2                      NaN  0.61850                   NaN     NaN      0.64045  
3                      NaN  0.91000                0.5719     NaN      0.57535  
4                      NaN  0.82475                   NaN  0.8479      0.82475

In [4]:
interaction_matrix = np.array(data.pivot(index = 'reviewer_id', columns ='listing_id', values = 'overall_avg').fillna(0))

In [6]:
print(interaction_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
#check if values exist
pd.DataFrame(interaction_matrix)[1].sum()

87.35422579365078

In [19]:
#y = pd.DataFrame(interaction_matrix)
#y.head()
data.pivot(index = 'reviewer_id', columns ='listing_id', values = 'overall_avg')
#x = data.loc[(data['listing_id']==35644) | (data['reviewer_id']==3712269),:]
#x.pivot(index = 'reviewer_id', columns ='listing_id', values = 'overall_avg')

listing_id   35644     38951     84581     88873     137808    162081    \
reviewer_id                                                               
1510              NaN       NaN       NaN       NaN       NaN       NaN   
6450              NaN       NaN       NaN       NaN       NaN       NaN   
6499              NaN       NaN       NaN       NaN       NaN       NaN   
6888              NaN       NaN       NaN       NaN       NaN       NaN   
7428              NaN       NaN       NaN       NaN       NaN       NaN   
8348              NaN       NaN       NaN       NaN       NaN       NaN   
10878             NaN       NaN       NaN       NaN       NaN       NaN   
11070             NaN       NaN       NaN       NaN       NaN       NaN   
12031             NaN       NaN       NaN       NaN       NaN       NaN   
12289             NaN       NaN       NaN       NaN       NaN       NaN   
13056             NaN       NaN       NaN       NaN       NaN       NaN   
15418             NaN       NaN       NaN       NaN       NaN       NaN   
16282             NaN       NaN       NaN       NaN       NaN       NaN   
16581             NaN       NaN       NaN       NaN       NaN       NaN   
16897             NaN       NaN       NaN       NaN       NaN       NaN   
17284             NaN       NaN       NaN       NaN       NaN       NaN   
17788             NaN       NaN       NaN       NaN       NaN       NaN   
18124             NaN       NaN       NaN       NaN       NaN       NaN   
20066             NaN       NaN       NaN       NaN       NaN       NaN   
20258             NaN       NaN       NaN       NaN       NaN       NaN   
21050             NaN       NaN       NaN       NaN       NaN       NaN   
21345             NaN       NaN       NaN       NaN       NaN       NaN   
21356             NaN       NaN       NaN       NaN       NaN       NaN   
21592             NaN       NaN       NaN       NaN       NaN       NaN   
21595             NaN       NaN       NaN       NaN       NaN       NaN   
22034             NaN       NaN       NaN       NaN       NaN       NaN   
22277             NaN       NaN       NaN       NaN       NaN       NaN   
22444             NaN       NaN       NaN       NaN       NaN       NaN   
22775             NaN       NaN       NaN       NaN       NaN       NaN   
22961             NaN       NaN       NaN       NaN       NaN       NaN   
...               ...       ...       ...       ...       ...       ...   
224921493         NaN       NaN       NaN       NaN       NaN       NaN   
224947715         NaN       NaN       NaN       NaN       NaN       NaN   
225062659         NaN       NaN       NaN       NaN       NaN       NaN   
225068903         NaN       NaN       NaN       NaN       NaN       NaN   
225069612         NaN       NaN       NaN       NaN       NaN       NaN   
225076174         NaN       NaN       NaN       NaN       NaN       NaN   
225164550         NaN       NaN       NaN       NaN       NaN       NaN   
225175617         NaN       NaN       NaN       NaN       NaN       NaN   
225187998         NaN       NaN       NaN       NaN       NaN       NaN   
225284075         NaN       NaN       NaN       NaN       NaN       NaN   
225295321         NaN       NaN       NaN       NaN       NaN       NaN   
225313744         NaN       NaN       NaN       NaN       NaN       NaN   
225332106         NaN       NaN       NaN       NaN       NaN       NaN   
225334043         NaN       NaN       NaN       NaN       NaN       NaN   
225334838         NaN       NaN       NaN       NaN       NaN       NaN   
225356445         NaN       NaN       NaN       NaN       NaN       NaN   
225461895         NaN       NaN       NaN       NaN       NaN       NaN   
225504727         NaN       NaN       NaN       NaN       NaN       NaN   
225530154         NaN       NaN       NaN       NaN       NaN       NaN   
225666125         NaN       NaN       NaN       NaN       NaN       NaN   
225673423         NaN    

In [25]:
#Count number of feature wise scores available for each reviewer
user_profile = pd.DataFrame({'reviewer_id':data.reviewer_id.unique()})
loop = ["experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food"]
for i in range(len(loop)):
    non_zero = data.loc[data[loop[i]]!=0]
    data_grouped = non_zero.groupby('reviewer_id')[loop[i]].apply(lambda x: pd.Series([x.count()])).unstack()
    print(i)
    user_profile = pd.merge(user_profile,data_grouped[0], how = 'left', on = 'reviewer_id')

0
1
2
3
4
5
6


In [29]:
user_profile.columns = ['reviewer_id',"experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food"]

In [34]:
#If available count of feature score > 0 for a user, mark as 1, else 0
user_profile_agg = user_profile
loop = ["experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food"]
for i in range(len(loop)):
    user_profile_agg.loc[user_profile_agg[loop[i]]>0,loop[i]] = 1

In [35]:
user_profile_agg.head()

reviewer_id  experience  view  décor_and_amenities  \
0      5394983           0   1.0                  1.0   
1      3712269           0   1.0                  1.0   
2      2908896           0   0.0                  0.0   
3      3941752           1   1.0                  1.0   
4      2735578           0   1.0                  1.0   

   neighborhood_and_access  host  weather_and_amenties  food  
0                      1.0     1                   0.0     1  
1                      1.0     1                   0.0     0  
2                      0.0     1                   0.0     0  
3                      0.0     1                   1.0     0  
4                      1.0     1                   0.0     1

In [48]:
listing_data = pd.DataFrame({'listing_id':data.listing_id.unique()})
loop = ["experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food","overall_avg"]
for i in range(len(loop)):
    data_grouped = data.groupby('listing_id')[loop[i]].apply(lambda x: pd.Series([(x < 0).sum(),(x > 0).sum()])).unstack()
    data_grouped['perc']=(data_grouped[1]-data_grouped[0])/(data_grouped[1]+data_grouped[0])
    print(i)
    listing_data = pd.merge(listing_data, data_grouped, how = 'left', on = 'listing_id')

0
1
2
3
4
5
6
7


In [49]:
listing_data.head()

listing_id  0_x  1_x    perc_x  0_y  1_y    perc_y  0_x  1_x    perc_x  \
0       35644    1   65  0.969697    1  130  0.984733    1  171  0.988372   
1       38951    0   30  1.000000    0   54  1.000000    3  105  0.944444   
2       84581    0    5  1.000000    0   14  1.000000    0   13  1.000000   
3       88873    2   25  0.851852    3   78  0.925926    7  235  0.942149   
4      137808    0   11  1.000000    2   20  0.818182    3  118  0.950413   

   ...    perc_x  0_y  1_y    perc_y  0_x  1_x    perc_x  0_y  1_y    perc_y  
0  ...  0.950000    0   60  1.000000    0   46  1.000000    3  198  0.970149  
1  ...  0.959184    3   36  0.846154    1   15  0.875000    0  135  1.000000  
2  ...  1.000000    0    7  1.000000    0    1  1.000000    0   16  1.000000  
3  ...  0.963636    5   63  0.852941    3   41  0.863636    2  296  0.986577  
4  ...  0.829787    5   18  0.565217    2   10  0.666667    4  139  0.944056  

[5 rows x 25 columns]

In [221]:
orig_data = pd.read_csv('D:\\GitHub\\Airbnb\\Recommendation\\Tasmania-detailed listings - final2.csv', error_bad_lines=False)
listing_profile = pd.merge(orig_data, listing_data, how = 'left', on = 'listing_id')

In [222]:
listing_profile.columns = ['listing_id','host_is_superhost','neighbourhood_cleansed','property_type','room_type','accommodates','bathrooms','bedrooms','beds','bed_type','price','security_deposit (% of price)','cleaning_fee (% of price)','minimum_nights','cancellation_policy',
"experience_p","experience_n","experience","view_p","view_n","view","décor_and_amenities_p","décor_and_amenities_n","décor_and_amenities",
"neighborhood_and_access_p","neighborhood_and_access_n","neighborhood_and_access","host_p","host_n","host",
"weather_and_amenties_p","weather_and_amenties_n","weather_and_amenties","food_p","food_n","food","overall_avg_p","overall_avg_n","overall_avg"]
features = ['listing_id','host_is_superhost','neighbourhood_cleansed','property_type','room_type','accommodates','bathrooms','bedrooms','beds','bed_type','price','security_deposit (% of price)','cleaning_fee (% of price)','minimum_nights','cancellation_policy',
"experience","view","décor_and_amenities","neighborhood_and_access","host","weather_and_amenties","food","overall_avg"]
listing_profile = listing_profile[features]

In [223]:
listing_profile.head()

listing_id host_is_superhost neighbourhood_cleansed property_type  \
0       35644                 t                 Hobart         House   
1       38951                 t                 Hobart     Townhouse   
2       84581                 f                Kentish         House   
3       88873                 t                 Hobart     Townhouse   
4      137808                 f             Launceston         House   

         room_type  accommodates  bathrooms  bedrooms  beds  bed_type  ...  \
0     Private room             2        1.5         1     1  Real Bed  ...   
1  Entire home/apt             4        1.0         2     2  Real Bed  ...   
2  Entire home/apt             9        2.0         3     6  Real Bed  ...   
3  Entire home/apt             4        1.0         2     3  Real Bed  ...   
4  Entire home/apt             9        1.5         2     7  Real Bed  ...   

  minimum_nights          cancellation_policy experience      view  \
0              1                     moderate   0.969697  0.984733   
1              2  strict_14_with_grace_period   1.000000  1.000000   
2              2  strict_14_with_grace_period   1.000000  1.000000   
3              1                     moderate   0.851852  0.925926   
4              1  strict_14_with_grace_period   1.000000  0.818182   

  décor_and_amenities  neighborhood_and_access      host  \
0            0.988372                 0.974359  0.950000   
1            0.944444                 0.983740  0.959184   
2            1.000000                 1.000000  1.000000   
3            0.942149                 0.961240  0.963636   
4            0.950413                 0.882353  0.829787   

   weather_and_amenties      food  overall_avg  
0              1.000000  1.000000     0.970149  
1              0.846154  0.875000     1.000000  
2              1.000000  1.000000     1.000000  
3              0.852941  0.863636     0.986577  
4              0.565217  0.666667     0.944056  

[5 rows x 23 columns]

In [224]:
listing_profile.to_csv('D:\\GitHub\\Airbnb\\Recommendation\\Tasmania-FinalDataset.csv')

In [225]:
listing_profile_trans = listing_profile.loc[:,listing_profile.columns != 'neighbourhood_cleansed']
listing_profile_trans.loc[listing_profile_trans['host_is_superhost']=='t','host_is_superhost'] = 1
listing_profile_trans.loc[listing_profile_trans['host_is_superhost']=='f','host_is_superhost'] = 0
listing_profile_trans.price = listing_profile_trans.price.str[1:].replace(',','', regex=True).astype(float)
listing_profile_trans['security_deposit (% of price)'] = listing_profile_trans['security_deposit (% of price)'].str[1:].replace(',','', regex=True).replace('%','', regex=True).astype(float)
listing_profile_trans['cleaning_fee (% of price)'] = listing_profile_trans['cleaning_fee (% of price)'].str[1:].replace(',','', regex=True).replace('%','', regex=True).astype(float)
#pd.get_dummies(listing_profile['host_is_superhost'], prefix='host_is_superhost')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pyd

In [226]:
text_columns = []
for c in listing_profile_trans.columns:
    if(listing_profile_trans[c].dtypes == 'object'):
        text_columns.append(c)
text_columns

['property_type', 'room_type', 'bed_type', 'cancellation_policy']

In [227]:
for c in text_columns:
    listing_profile_trans = pd.concat([listing_profile_trans,pd.get_dummies(listing_profile_trans[c], prefix=c,dummy_na=True)],axis=1).drop([c],axis=1)
    print("Created dummies for", c)

Created dummies for property_type
Created dummies for room_type
Created dummies for bed_type
Created dummies for cancellation_policy


In [228]:
listing_profile_trans.columns

Index(['listing_id', 'host_is_superhost', 'accommodates', 'bathrooms',
       'bedrooms', 'beds', 'price', 'security_deposit (% of price)',
       'cleaning_fee (% of price)', 'minimum_nights', 'experience', 'view',
       'décor_and_amenities', 'neighborhood_and_access', 'host',
       'weather_and_amenties', 'food', 'overall_avg',
       'property_type_Aparthotel', 'property_type_Apartment',
       'property_type_Barn', 'property_type_Bed and breakfast',
       'property_type_Boat', 'property_type_Boutique hotel',
       'property_type_Bungalow', 'property_type_Bus', 'property_type_Cabin',
       'property_type_Camper/RV', 'property_type_Campsite',
       'property_type_Casa particular (Cuba)', 'property_type_Castle',
       'property_type_Chalet', 'property_type_Condominium',
       'property_type_Cottage', 'property_type_Dome house',
       'property_type_Earth house', 'property_type_Farm stay',
       'property_type_Guest suite', 'property_type_Guesthouse',
       'property_type_H

In [229]:
listing_profile_trans.dtypes

listing_id                                           int64
host_is_superhost                                    int64
accommodates                                         int64
bathrooms                                          float64
bedrooms                                             int64
beds                                                 int64
price                                              float64
security_deposit (% of price)                      float64
cleaning_fee (% of price)                          float64
minimum_nights                                       int64
experience                                         float64
view                                               float64
décor_and_amenities                                float64
neighborhood_and_access                            float64
host                                               float64
weather_and_amenties                               float64
food                                               float

In [245]:
listing_profile_trans.head()

listing_id  host_is_superhost  accommodates  bathrooms  bedrooms  beds  \
0       35644                  1             2        1.5         1     1   
1       38951                  1             4        1.0         2     2   
2       84581                  0             9        2.0         3     6   
3       88873                  1             4        1.0         2     3   
4      137808                  0             9        1.5         2     7   

   price  security_deposit (% of price)  cleaning_fee (% of price)  \
0   55.0                            0.0                       4.55   
1  190.0                            0.0                       0.00   
2  295.0                            0.0                       0.00   
3  125.0                            0.0                       0.00   
4  145.0                            0.0                       0.00   

   minimum_nights  ...  bed_type_Futon  bed_type_Pull-out Sofa  \
0               1  ...               0                       0   
1               2  ...               0                       0   
2               2  ...               0                       0   
3               1  ...               0                       0   
4               1  ...               0                       0   

   bed_type_Real Bed  bed_type_nan  cancellation_policy_flexible  \
0                  1             0                             0   
1                  1             0                             0   
2                  1             0                             0   
3                  1             0                             0   
4                  1             0                             0   

   cancellation_policy_moderate  \
0                             1   
1                             0   
2                             0   
3                             1   
4                             0   

   cancellation_policy_strict_14_with_grace_period  \
0                                                0   
1                                                1   
2                                                1   
3                                                0   
4                                                1   

   cancellation_policy_super_strict_30  cancellation_policy_super_strict_60  \
0                                    0                                    0   
1                                    0                                    0   
2                                    0                                    0   
3                                    0                                    0   
4                                    0                                    0   

   cancellation_policy_nan  
0                        0  
1                        0  
2                        0  
3                        0  
4                        0  

[5 rows x 72 columns]

In [230]:
#user_matrix = np.array(user_profile_agg)
#listing_matrix = np.array(listing_profile)
user_matrix = user_profile_agg.iloc[:,1:8].values
listing_matrix = listing_profile_trans.iloc[:,1:71].fillna(0).values

In [189]:
#Create dictionary for column headers
user_profile_dict = dict(zip([ i for i in range(0,7)],user_profile_agg.columns[1:8]))
print(user_profile_dict)
listing_profile_dict = dict(zip([ i for i in range(0,70)],listing_profile_trans.columns[1:71]))
print(listing_profile_dict)

{0: 'experience', 1: 'view', 2: 'décor_and_amenities', 3: 'neighborhood_and_access', 4: 'host', 5: 'weather_and_amenties', 6: 'food'}
{0: 'host_is_superhost', 1: 'accommodates', 2: 'bathrooms', 3: 'bedrooms', 4: 'beds', 5: 'price', 6: 'security_deposit (% of price)', 7: 'cleaning_fee (% of price)', 8: 'minimum_nights', 9: 'experience', 10: 'view', 11: 'décor_and_amenities', 12: 'neighborhood_and_access', 13: 'host', 14: 'weather_and_amenties', 15: 'food', 16: 'overall_avg', 17: 'property_type_Aparthotel', 18: 'property_type_Apartment', 19: 'property_type_Barn', 20: 'property_type_Bed and breakfast', 21: 'property_type_Boat', 22: 'property_type_Boutique hotel', 23: 'property_type_Bungalow', 24: 'property_type_Bus', 25: 'property_type_Cabin', 26: 'property_type_Camper/RV', 27: 'property_type_Campsite', 28: 'property_type_Casa particular (Cuba)', 29: 'property_type_Castle', 30: 'property_type_Chalet', 31: 'property_type_Condominium', 32: 'property_type_Cottage', 33: 'property_type_Dome ho

In [231]:
print(user_matrix)
print(listing_matrix)

[[0. 1. 1. ... 1. 0. 1.]
 [0. 1. 1. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 1. 1. ... 1. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
[[1.  2.  1.5 ... 0.  0.  0. ]
 [1.  4.  1.  ... 1.  0.  0. ]
 [0.  9.  2.  ... 1.  0.  0. ]
 ...
 [0.  2.  1.  ... 0.  0.  0. ]
 [0.  2.  1.  ... 0.  0.  0. ]
 [1.  8.  1.5 ... 0.  0.  0. ]]


In [232]:
user_sp_matrix = scipy.sparse.csr_matrix(user_matrix)
print("Created user sparse matrix")
listing_sp_matrix = scipy.sparse.csr_matrix(listing_matrix)
print("Created listing sparse matrix")

Created user sparse matrix
Created listing sparse matrix


In [ ]:
#TODO:Train and test split
#     Check if dimensions of train, test, user sp matrix and item sp matrix are as expected
#     Create listings df with buckets for numerical columns
#     Create user df with text as features

In [281]:
listing_profile_text = listing_profile.loc[:,listing_profile.columns != 'neighbourhood_cleansed']
listing_profile_text.price = listing_profile_text.price.str[1:].replace(',','', regex=True).astype(float)
listing_profile_text['security_deposit (% of price)'] = listing_profile_text['security_deposit (% of price)'].str[1:].replace(',','', regex=True).replace('%','', regex=True).astype(float)
listing_profile_text['cleaning_fee (% of price)'] = listing_profile_text['cleaning_fee (% of price)'].str[1:].replace(',','', regex=True).replace('%','', regex=True).astype(float)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [283]:
text_c = []
for c in listing_profile_text.columns:
    if(listing_profile_text[c].dtypes == 'object'):
        text_c.append(c)
text_c

['host_is_superhost',
 'property_type',
 'room_type',
 'bed_type',
 'cancellation_policy']

In [350]:
dataset = Dataset()
dataset.fit((user_profile_agg['reviewer_id']),
            (listing_profile_text['listing_id']))
num_users, num_items = dataset.interactions_shape()
print('Num users: {}, num_items {}.'.format(num_users, num_items))

Num users: 125747, num_items 5073.


In [234]:
data.head()

listing_id  reviewer_id  experience     view  décor_and_amenities  \
0       35644      5394983         NaN  0.91525               0.9371   
1       35644      3712269         NaN  0.82710               0.8271   
2       35644      2908896         NaN      NaN                  NaN   
3       35644      3941752      0.5719  0.30890               0.5106   
4       35644      2735578         NaN      NaN                  NaN   

   neighborhood_and_access     host  weather_and_amenties    food  overall_avg  
0                   0.5115 -0.29600                   NaN  0.8225      0.58925  
1                   0.8271  0.54130                   NaN     NaN      0.59010  
2                      NaN  0.61850                   NaN     NaN      0.64045  
3                      NaN  0.91000                0.5719     NaN      0.57535  
4                      NaN  0.82475                   NaN  0.8479      0.82475

In [351]:
(interactions, weights) = dataset.build_interactions(((data.loc[i,'reviewer_id'],data.loc[i,'listing_id'],data.loc[i,'overall_avg'])
                                                      for i in range(0,len(data))))
print(repr(interactions))

<125747x5073 sparse matrix of type '<class 'numpy.int32'>'
	with 177723 stored elements in COOrdinate format>


In [348]:
temp_list = []
for c in text_c:
    print(listing_profile_text[c].unique())
    temp_loop = list(listing_profile_text[c].unique())
    for x in temp_loop:
        temp_list.append(x)

['t' 'f']
['House' 'Townhouse' 'Guest suite' 'Bed and breakfast' 'Loft' 'Guesthouse'
 'Apartment' 'Bungalow' 'Cabin' 'Cottage' 'Chalet' 'Earth house'
 'Condominium' 'Farm stay' 'Other' 'Serviced apartment' 'Treehouse'
 'Camper/RV' 'Boutique hotel' 'Tiny house' 'Barn' 'Nature lodge' 'Villa'
 'Tipi' 'Hostel' 'Castle' 'Hut' 'Hotel' 'Yurt' 'Tent' 'Island' 'Bus'
 'Aparthotel' 'Casa particular (Cuba)' 'Dome house' 'Campsite'
 'Vacation home' 'Boat']
['Private room' 'Entire home/apt' 'Shared room']
['Real Bed' 'Pull-out Sofa' 'Futon' 'Airbed']
['moderate' 'strict_14_with_grace_period' 'super_strict_30' 'flexible'
 'super_strict_60']


In [349]:
temp_list

['t',
 'f',
 'House',
 'Townhouse',
 'Guest suite',
 'Bed and breakfast',
 'Loft',
 'Guesthouse',
 'Apartment',
 'Bungalow',
 'Cabin',
 'Cottage',
 'Chalet',
 'Earth house',
 'Condominium',
 'Farm stay',
 'Other',
 'Serviced apartment',
 'Treehouse',
 'Camper/RV',
 'Boutique hotel',
 'Tiny house',
 'Barn',
 'Nature lodge',
 'Villa',
 'Tipi',
 'Hostel',
 'Castle',
 'Hut',
 'Hotel',
 'Yurt',
 'Tent',
 'Island',
 'Bus',
 'Aparthotel',
 'Casa particular (Cuba)',
 'Dome house',
 'Campsite',
 'Vacation home',
 'Boat',
 'Private room',
 'Entire home/apt',
 'Shared room',
 'Real Bed',
 'Pull-out Sofa',
 'Futon',
 'Airbed',
 'moderate',
 'strict_14_with_grace_period',
 'super_strict_30',
 'flexible',
 'super_strict_60']

In [352]:
dataset.fit_partial(items=(listing_profile_text['listing_id']),
                    item_features=(tuple(temp_list) ))

In [323]:
dataset.item_features_shape()

(5073, 5362)

In [353]:
item_features = dataset.build_item_features((
                                                (listing_profile_text.loc[i,'listing_id'], list(listing_profile_text.loc[i,text_c].values)) for i in range(0,len(listing_profile_text))
                                            ))
print(repr(item_features))

<5073x5125 sparse matrix of type '<class 'numpy.float32'>'
	with 30438 stored elements in Compressed Sparse Row format>


In [242]:
x=(data.loc[1,:])
type(x)

pandas.core.series.Series

In [358]:
NUM_COMPONENTS = 30
EPOCHS = 20
NUM_THREADS = 2

model = LightFM(loss = 'bpr', no_components=NUM_COMPONENTS) 
%time model.fit(interactions,item_features= item_features,epochs=EPOCHS,num_threads=NUM_THREADS)

Wall time: 1min 21s


In [361]:
test_u =[3024649]
test_l=[35644]
model.predict(test_u,test_l)

ValueError: The user feature matrix specifies more features than there are estimated feature embeddings: 125747 vs 3024650.